version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: cmd/labs/Dockerfile
    container_name: labs
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: labs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
